export const mockFilterSegments = {
  chanel: {
    order: 0,
    type: 0,
    key: 'brands',
    gender: null,
    value: 43279979,
    valueUpperBound: 0,
    slug: 'chanel',
    description: 'CHANEL',
    deep: 0,
    parentId: 0,
    fromQueryString: false,
    negativeFilter: false,
    facetId: 'brands_43279979',
  },
  belts: {
    order: 0,
    type: 6,
    key: 'categories',
    gender: 1,
    value: 136000,
    valueUpperBound: 0,
    slug: 'accessories-belts',
    description: 'Belts',
    deep: 2,
    parentId: 135972,
    fromQueryString: true,
    negativeFilter: false,
    prefixValue: '',
    facetId: 'categories_136000',
  },
  beauty: {
    order: 0,
    type: 6,
    key: 'categories',
    gender: 0,
    value: 137569,
    valueUpperBound: 0,
    slug: 'beauty',
    description: 'Beauty',
    deep: 1,
    parentId: 0,
    fromQueryString: true,
    negativeFilter: false,
    facetId: 'categories_137569',
  },
  pricetype: {
    order: 0,
    type: 14,
    key: 'pricetype',
    gender: null,
    value: 1,
    valueUpperBound: 0,
    slug: 'sale',
    description: 'Sale',
    deep: 0,
    parentId: 0,
    fromQueryString: false,
    negativeFilter: false,
    facetId: 'pricetype_1',
  },
  baubles: {
    order: 0,
    type: 6,
    key: 'categories',
    gender: 0,
    value: 141514,
    valueUpperBound: 0,
    slug: 'christmas-decorations-baubles',
    description: 'Baubles',
    deep: 3,
    parentId: 141508,
    fromQueryString: false,
    negativeFilter: false,
    prefixValue: null,
  },
};

export const mockInitialState = {
  locale: {
    countryCode: 'US',
    countries: {
      error: null,
      isLoading: false,
    },
    currencies: {
      error: null,
      isLoading: false,
    },
  },
  entities: {
    countries: {
      US: {
        code: 'US',
        cultures: ['en-US'],
        currencies: [
          {
            id: 2,
            name: 'United States Dollar',
            isoCode: 'USD',
            cultureCode: 'en-US',
            symbol: '$',
          },
        ],
        structures: ['/en-us'],
        newsletterSubscriptionOptionDefault: true,
        platformId: 216,
        defaultCulture: 'en-US',
        defaultSubfolder: '/en-us',
        name: 'United States',
        nativeName: 'United States',
        isDefault: true,
        isCountryDefault: true,
        continentId: 5,
      },
    },
    facets: {
      price_1_1100: {
        value: 1,
        valueUpperBound: 1100,
        description: null,
        slug: null,
        url: '?price=1',
        parentId: 'price_0',
        _isDisabled: false,
        _isActive: false,
        groupsOn: 0,
        count: 0,
        id: 'price_1_1100',
      },
    },
  },
};
