export { default as deleteUserAddress } from './deleteUserAddress';
export { default as deleteUserDefaultContactAddress } from './deleteUserDefaultContactAddress';
export { default as getUserAddress } from './getUserAddress';
export { default as getUserAddresses } from './getUserAddresses';
export { default as getUserDefaultContactAddress } from './getUserDefaultContactAddress';
export { default as postUserAddress } from './postUserAddress';
export { default as putUserAddress } from './putUserAddress';
export { default as putUserDefaultBillingAddress } from './putUserDefaultBillingAddress';
export { default as putUserDefaultContactAddress } from './putUserDefaultContactAddress';
export { default as putUserDefaultShippingAddress } from './putUserDefaultShippingAddress';
export * from './types';
